version: 2
checks:
  file-lines:
    enabled: true
    config:
      threshold: 800
  method-count:
    enabled: true
    config:
      threshold: 100
  method-lines:
    enabled: true
    config:
      threshold: 35
exclude_patterns:
  - "samples/kaleidescope/"
