inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-performance
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - 'samples/**/*'
    - 'lib/llvm/config.rb'
    - 'tmp/*'
    - vendor/bundle/**/*
    - lib/llvm/core/pass_manager.rb
    - test/pass_manager_builder_test.rb
    - lib/llvm/transforms/**

# Style
Style/ClassAndModuleChildren:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/NegatedWhile:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - lib/llvm/**/*_ffi.rb

Style/Alias:
  EnforcedStyle: prefer_alias_method

# Layout
Layout/EndAlignment:
  AutoCorrect: true
  EnforcedStyleAlignWith: variable

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/CaseIndentation:
  Enabled: true
  EnforcedStyle: end

# Exceptions
Style:
  Exclude:
    - 'lib/**/*ffi.rb'

Layout/IndentationWidth:
  Exclude:
    - 'lib/**/*ffi.rb'

Style/RedundantBegin:
  Exclude:
    - 'lib/**/*ffi.rb'
    - 'ext/ruby-llvm-support/Rakefile'

# Naming
Naming/MethodName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
  Exclude:
    - 'lib/**/*ffi.rb'
    - 'ext/ruby-llvm-support/Rakefile'

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
  Exclude:
    - 'lib/**/*ffi.rb'
    - 'ext/ruby-llvm-support/Rakefile'

# Metrics

Metrics/ClassLength:
  Max: 210
  CountAsOne: ['array', 'hash']
  Exclude:
    - 'lib/llvm/core/builder.rb'

# Gemspec

# Not sold on usefulness: https://github.com/rubocop/rubocop/pull/11469
Gemspec/DevelopmentDependencies:
  Enabled: false

Style/AccessModifierDeclarations:
  Enabled: false

# this one is wrong
Style/DoubleNegation:
  Enabled: false

Style/YodaCondition:
  Enabled: false

Style/TrailingUnderscoreVariable:
  Enabled: false

Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: false

Naming/PredicateMethod:
  Enabled: false
