inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - 'samples/**/*'
    - 'lib/llvm/config.rb'
    - 'tmp/*'

# Style
Style/ClassAndModuleChildren:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/NegatedWhile:
  Enabled: false

# Layout
Layout/EndAlignment:
  AutoCorrect: true
  EnforcedStyleAlignWith: variable

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/CaseIndentation:
  Enabled: true
  EnforcedStyle: end

# Exceptions
Style:
  Exclude:
    - 'lib/**/*ffi.rb'

Layout/IndentationWidth:
  Exclude:
    - 'lib/**/*ffi.rb'

Style/RedundantBegin:
  Exclude:
    - 'lib/**/*ffi.rb'
    - 'ext/ruby-llvm-support/Rakefile'

# Naming
Naming/MethodName:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
  Exclude:
    - 'lib/**/*ffi.rb'
    - 'ext/ruby-llvm-support/Rakefile'

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
  Exclude:
    - 'lib/**/*ffi.rb'
    - 'ext/ruby-llvm-support/Rakefile'

# Offense count: 1
# Configuration parameters: CountComments, CountAsOne.
Metrics/ClassLength:
  Exclude:
    - 'lib/llvm/core/builder.rb'
    - 'test/instruction_test.rb'
