# typed: true
# frozen_string_literal: true

require "llvm/analysis"
require "llvm/analysis_ffi"
require "llvm/config"
require "llvm/core"
require "llvm/core/attribute"
require "llvm/core/bitcode"
require "llvm/core/bitcode_ffi"
require "llvm/core/builder"
require "llvm/core/context"
require "llvm/core/module"
require "llvm/core/type"
require "llvm/core/value"
require "llvm/core_ffi"
require "llvm/core_ffi_v2"
require "llvm/execution_engine"
require "llvm/execution_engine_ffi"
require "llvm/linker"
require "llvm/linker_ffi"
require "llvm/lljit"
require "llvm/pass_builder"
require "llvm/support"
require "llvm/target"
require "llvm/target_ffi"
require "llvm/version"

require "minitest/spec"
