require 'rake/clean'
require 'rubygems'
require 'ffi'

CC = "g++"
LLVM_CONFIG = `llvm-config-3.2 --cxxflags --ldflags --libs all`.gsub("\n"," ")
OUTPUT = FFI.map_library_name "RubyLLVMSupport-3.2.0"
OUTPUT_DIR = "../../lib"
SRC = "support.cpp"
CLOBBER.include(OUTPUT)

task :default => [:build]

desc "Build the shared library"
task :build => [OUTPUT]

file OUTPUT => [SRC] do
  sh "#{CC} -shared #{SRC} #{LLVM_CONFIG} -o #{OUTPUT_DIR}/#{OUTPUT}"
end
