# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module ::MakeMakefile; end
module LLVM::Int1; end
module LLVM::Int16; end
module LLVM::Int19; end
module LLVM::Int256; end
module LLVM::Int32; end
module LLVM::Int64; end
module LLVM::Int8; end
module VarExprAST::BodyVal; end
