name: Matrix Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04, macos-13, macos-14]
        ruby: ['2.7', '3.0', '3.1', '3.2', '3.3']
    continue-on-error: ${{ endsWith(matrix.ruby, 'head') || matrix.ruby == 'debug' }}
    steps:
      - name: Check for LLVM on Homebrew
        id: homebrew_check
        if: startsWith(matrix.os, 'macos')
        run: |
          brew info llvm19 || echo "brew=true" >> "$GITHUB_OUTPUT"
      - name: Install LLVM on macos
        if: steps.step1.outputs.brew == 'true'
        run: |
          brew update --auto-update
          brew install llvm@19
        env:
          HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
      - name: 'MacOS setup'
        id: macos_setup
        if: steps.step1.outputs.brew == 'true'
        run: |
          echo "$(brew --prefix llvm@19)/bin" >> $GITHUB_PATH
          sudo mkdir -p /opt/local/
          sudo ln -s $(brew --prefix llvm@19)/lib /opt/local/lib
          # ffi will only look for files in a small set of directories, so llvm needs to be there
          # https://github.com/ffi/ffi/blob/master/lib/ffi/dynamic_library.rb#L33
          # /usr/lib /usr/local/lib /opt/local/lib /opt/homebrew/lib
          # this uses /opt/local/lib -> /usr/local/opt/llvm/lib
          echo "setup=true" >> "$GITHUB_OUTPUT"
      - name: 'MacOS debug'
        if: steps.step1.outputs.brew == 'true'
        run: |
          echo $(brew --repository)
          echo $(brew --prefix llvm@19)
          echo $(brew info llvm@19)
          echo "$PATH"
          echo $(llvm-config --ldflags)
          ls -l $(brew --prefix llvm@19)/lib/libLLVM.dylib
          ls -l /opt/local/lib/libLLVM.dylib
      - name: Install LLVM on ubuntu
        id: ubuntu_setup
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt install libyaml-dev
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 19
          # TODO: [LLVM 19] remove this patch when packaging is fixed
          sudo ln -s /usr/lib/llvm-19/lib/libLLVM.so.1 /usr/lib/x86_64-linux-gnu/libLLVM-19.so.1
          echo "setup=true" >> "$GITHUB_OUTPUT"
      - name: 'Ubuntu debug'
        if: steps.ubuntu_setup.outputs.setup == 'true'
        run: |
          clang --version
          which clang
          ls -alF /usr/lib/llvm-*/include/
          dpkg -l | egrep 'c\+\+|g\+\+|gcc|llvm|build-essential'
          ls -alF /usr/include/c++/*/cstddef
          ls -alF /usr/lib/llvm-*/include/
      - uses: actions/checkout@v4
        if: steps.macos_setup.outputs.setup == 'true' || steps.ubuntu_setup.outputs.setup == 'true'
      - uses: ruby/setup-ruby@v1
        if: steps.macos_setup.outputs.setup == 'true' || steps.ubuntu_setup.outputs.setup == 'true'
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: cd ext/ruby-llvm-support && bundle exec rake
        name: "Build support library"
        if: steps.macos_setup.outputs.setup == 'true' || steps.ubuntu_setup.outputs.setup == 'true'
      - run: bundle exec rake
        name: "Run tests"
        if: steps.macos_setup.outputs.setup == 'true' || steps.ubuntu_setup.outputs.setup == 'true'
      - run: bundle exec rake test:samples
        name: "Run samples"
        if: steps.macos_setup.outputs.setup == 'true' || steps.ubuntu_setup.outputs.setup == 'true'
