name: Matrix Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04, macos-13, macos-14, macos-15]
        ruby: ['3.2', '3.3', '3.4']
    continue-on-error: ${{ endsWith(matrix.ruby, 'head') || matrix.ruby == 'debug' }}
    steps:
      - name: Install LLVM on macos
        if: startsWith(matrix.os, 'macos')
        id: macos_setup
        run: |
          echo "setup=false" >> "$GITHUB_OUTPUT"
          # brew update --auto-update
          brew install llvm@20
          echo "$(brew --prefix llvm@20)/bin" >> $GITHUB_PATH
          sudo mkdir -p /opt/local/
          sudo ln -s $(brew --prefix llvm@20)/lib /opt/local/lib
          # ffi will only look for files in a small set of directories, so llvm needs to be there
          # https://github.com/ffi/ffi/blob/master/lib/ffi/dynamic_library.rb#L33
          # /usr/lib /usr/local/lib /opt/local/lib /opt/homebrew/lib
          # this uses /opt/local/lib -> /usr/local/opt/llvm/lib
          echo "setup=true" >> "$GITHUB_OUTPUT"
      - name: 'MacOS debug'
        if: steps.macos_setup.setup == 'false'
        run: |
          echo $(brew --repository)
          echo $(brew --prefix llvm@20)
          echo $(brew info llvm@20)
          echo "$PATH"
          echo $(llvm-config --ldflags)
          ls -l $(brew --prefix llvm@20)/lib/libLLVM.dylib
          ls -l /opt/local/lib/libLLVM.dylib
      - name: Install LLVM on ubuntu
        id: ubuntu_setup
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          echo "setup=false" >> "$GITHUB_OUTPUT"
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 20
          # sudo apt-get install -y libpolly-20-dev
          echo "setup=true" >> "$GITHUB_OUTPUT"
      - uses: actions/checkout@v4
        if: steps.macos_setup.outputs.setup == 'true' || steps.ubuntu_setup.outputs.setup == 'true'
      - uses: ruby/setup-ruby@v1
        if: steps.macos_setup.outputs.setup == 'true' || steps.ubuntu_setup.outputs.setup == 'true'
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: cd ext/ruby-llvm-support && bundle exec rake
        name: "Build support library"
        if: steps.macos_setup.outputs.setup == 'true' || steps.ubuntu_setup.outputs.setup == 'true'
      - run: bundle exec rake
        name: "Run tests"
        if: steps.macos_setup.outputs.setup == 'true' || steps.ubuntu_setup.outputs.setup == 'true'
      - run: bundle exec rake test:samples
        name: "Run samples"
        if: steps.macos_setup.outputs.setup == 'true' || steps.ubuntu_setup.outputs.setup == 'true'
