name: Matrix Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        # TOD: os: [ubuntu, macos]
        os: [ubuntu]
        ruby: [2.7, 3.0]
    continue-on-error: ${{ endsWith(matrix.ruby, 'head') || matrix.ruby == 'debug' }}
    steps:
      - name: Install LLVM on macos
        if: matrix.os == 'macos'
        run: |
          brew install llvm@15
          echo "$(brew --prefix llvm)/bin" >> $GITHUB_PATH
          export LDFLAGS="-L$(brew --prefix llvm)/lib"
          export CPPFLAGS="-I$(brew --prefix llvm)/include"
          echo "$LDFLAGS"
          echo "$CPPFLAGS"
      - name: Install LLVM on ubuntu
        if: matrix.os == 'ubuntu'
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 15
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: bundle install
      - run: |
          pushd .
          cd ext/ruby-llvm-support && rake
          popd
          bundle exec rake
        if: matrix.os == 'ubuntu'
      - run: |
          echo "$LDFLAGS"
          echo "$CPPFLAGS"
          pushd .
          cd ext/ruby-llvm-support && rake
          popd
          bundle exec rake
        env:
          LDFLAGS: "-L/usr/local/opt/llvm/lib"
          CPPFLAGS: "-I/usr/local/opt/llvm/include"
        if: matrix.os == 'macos'
